---
- hosts: all
  tasks:
  - name: Install s3fs support
    apt:
      name: s3fs
      state: present

  - name: Ansible create file
    file:
      path: "~/.passwd-s3fs"
      state: touch
      mode: '0600'

  - name: Set security credentials
    copy:
      content: "GU4VSAQR2BEKBWAUETRG:/OQPYm94tXwQYbyUs72ULXffwRXUiydtqnZDT6Wfc0Q"
      dest: "~/.passwd-s3fs"

  - name: Create cloud storage mount folder
    file:
        path: /backup/CS
        state: directory
        mode: '0755'

  - name: Create local folder for daily DB backup
    file:
        path: /backup/daily_db
        state: directory
        mode: '0755'

  - name: Create local folder for weekly full backup
    file:
        path: /backup/weekly_files
        state: directory
        mode: '0755'

  - name: Test mount cloud storage
    shell: s3fs wsn-backups /backup/CS -o passwd_file=.passwd-s3fs -o url=https://fra1.digitaloceanspaces.com -o use_path_request_style

  - name: Umount cloud storage
    shell: umount /backup/CS
